import { FashionItem } from "./types";

export const INITIAL_ITEMS: FashionItem[] = [
  {
    id: "1",
    title: "Vintage Paisley Silk Tie",
    price: 45.0,
    currency: "$",
    imageUrl: "/img/1.jpg",
    seller: {
      name: "Arthur Sterling",
      bio: "Collector of mid-century menswear and rare accessories.",
      avatar: "/img/1.jpg",
    },
    details: "Hand-sewn silk tie from the 1960s. Excellent condition.",
  },
  {
    id: "2",
    title: "Queen World Tour 76 Tee",
    price: 185.0,
    currency: "$",
    imageUrl: "/img/2.jpg",
    seller: {
      name: "Melody Rock",
      bio: "Vintage band tee enthusiast and concert memorabilia archivist.",
      avatar: "/img/2.jpg",
    },
    details: "Authentic 1976 world tour t-shirt. Rare light blue colorway.",
  },
  {
    id: "3",
    title: "Vivienne Westwood Beret",
    price: 210.0,
    currency: "$",
    imageUrl: "/img/3.jpg",
    seller: {
      name: "Julianne V.",
      bio: "Curator of avant-garde European fashion.",
      avatar: "/img/3.jpg",
    },
    details: "Signature orb embroidered beret in cream wool.",
  },
  {
    id: "4",
    title: "Baggu Sandy Liang Packing Cubes",
    price: 115.0,
    currency: "$",
    imageUrl: "/img/4.jpg",
    seller: {
      name: "Ellie Warnke",
      bio: "Content creator and fashion design student.",
      avatar: "/img/4.jpg",
    },
    details: "Limited edition collaboration. Set of three brand new with tags.",
    isSold: true,
  },
  {
    id: "5",
    title: "90s Oversized Leather Jacket",
    price: 320.0,
    currency: "$",
    imageUrl: "/img/5.jpg",
    seller: {
      name: "Nico Hudson",
      bio: "Sourcing the best leather and denim from the Pacific Northwest.",
      avatar: "/img/5.jpg",
    },
    details: "Heavyweight grain leather with a perfectly aged patina.",
  },
  {
    id: "6",
    title: "Handmade Crochet Cardigan",
    price: 95.0,
    currency: "$",
    imageUrl: "/img/6.jpg",
    seller: {
      name: "Sophie Made",
      bio: "Fiber artist specializing in sustainable slow fashion.",
      avatar: "/img/6.jpg",
    },
    details: "One-of-a-kind patchwork design made from recycled cotton yarn.",
  },
  {
    id: "7",
    title: "Prada Vintage Nylon Bag",
    price: 450.0,
    currency: "$",
    imageUrl: "/img/7.jpg",
    seller: {
      name: "Luxury Loft",
      bio: "Authentic pre-loved designer handbags.",
      avatar: "/img/7.jpg",
    },
    details: "Classic black nylon with silver-toned hardware.",
  },
  {
    id: "8",
    title: "Hand-Painted Denim Jacket",
    price: 150.0,
    currency: "$",
    imageUrl: "/img/8.jpg",
    seller: {
      name: "ArtWear",
      bio: "Turning vintage denim into wearable canvases.",
      avatar: "/img/8.jpg",
    },
    details: "Levi's 501 jacket with custom floral back piece.",
  },
  {
    id: "9",
    title: "Y2K Cyberpunk Sunglasses",
    price: 65.0,
    currency: "$",
    imageUrl: "/img/9.jpg",
    seller: {
      name: "Future Retro",
      bio: "Specializing in millennium-era eyewear.",
      avatar: "/img/9.jpg",
    },
    details: "Wrap-around frames with blue mirrored lenses.",
  },
];
