import { PolaroidImage } from "./types";

export const POLAROID_IMAGES: PolaroidImage[] = [
  {
    id: "landscape-1",
    url: "/img/1.jpg",
    top: "32%",
    left: "30%",
    width: "30%",
    rotation: "0deg",
    zIndex: 10,
  },
  {
    id: "vertical-1",
    url: "/img/2.jpg",
    top: "20%",
    left: "49%",
    width: "18%",
    rotation: "0deg",
    zIndex: 30,
  },
  {
    id: "vertical-2",
    url: "/img/3.jpg",
    top: "23%",
    left: "78%",
    width: "18%",
    rotation: "0deg",
    zIndex: 25,
  },
  {
    id: "landscape-3",
    url: "/img/4.jpg",
    top: "35%",
    left: "68%",
    width: "30%",
    rotation: "0deg",
    zIndex: 5,
  },
  {
    id: "vertical-3",
    url: "/img/5.jpg",
    top: "50%",
    left: "21%",
    width: "18%",
    rotation: "0deg",
    zIndex: 35,
  },
  {
    id: "landscape-2",
    url: "/img/6.jpg",
    top: "59%",
    left: "42%",
    width: "30%",
    rotation: "0deg",
    zIndex: 15,
  },
  {
    id: "landscape-4",
    url: "/img/7.jpg",
    top: "62%",
    left: "75%",
    width: "30%",
    rotation: "0deg",
    zIndex: 8,
  },
  {
    id: "vertical-4",
    url: "/img/8.jpg",
    top: "72%",
    left: "56%",
    width: "18%",
    rotation: "0deg",
    zIndex: 40,
  },
];
